export enum FontSize {
    VERYSMALL = '12px',
    SMALLXS='6px',
    SMALLXXS='7px',
    SMALL = '8px',
    SMALLS = '9px',
    SMALLX = '10px',
    SMALLXX = '11px',
    NORMALXS = '12px',
    NORMAL = '14px',
    MIDIUMXS = '15px',
    MIDIUM = '16px',
    MIDPLUS = '18px',
    GRANDEMIDIUM= '20px',
    BIGXS = '23px',
    BIG = '25px',
    VERY_BIG = '26px',
    LARGE = '42px',
}
