export enum FontSize {
    VERYSMALL = 12,
    SMALLXS=6,
    SMALLXXS=7,
    SMALL = 8,
    SMALLS = 9,
    SMALLX = 10,
    SMALLXX =11,
    NORMAL = 14,
    MIDIUM = 16,
    MIDPLUS = 18,
    GRANDEMIDIUM= 20,
    BIG = 25,
    VERY_BIG = 26,
    LARGE = 42,
}
