export enum FontSize {
    MEDIUM_BIG = "23px",
    VERY_SMALL = '9px',
    small="13px",
    SMALL = '15px',
    NORMAL = '16px',
    MEDIUM = '20px',
    BIG = '30px',
    paragraphDesktop = '18px',
    paragraphMobile = '16px',
    headerDesktop = '32px',
    headerMobile = '30px',
    subtitleDesktop = '22px',
    subtitleMobile = '20px',
    Vsm = "11px",
    sm = "12px",
    medium= "16px",
    big = "20px",
    VERY_BIG = "23px"
}