export enum FontSize {
  XXXXXXSMALL = "8px",
  XXXXXSMALL = "9px",
  VERY_SMALL = "10px",
  XXXXSMALL = "11px",
  XXXSMALL = "12px",
  XSMALL = "14px",
  SMALL = "15px",
  XXXXMEDIUM = "16px",
  XXMEDIUM = "18px",
  MEDIUM = "20px",
  XXMEDIUM_L = "23px",
  XMEDIUM_L = "24px",
  MEDIUM_L = "25px",
  XXBIG = "28px",
  BIG = "30px",
  VERY_BIG = "35px",
  HUGE = "40px",
}
