export enum FontSize {
    paragraphDesktop = '18px',
    paragraphMobile = '16px',
    headerDesktop = '32px',
    headerMobile = '30px',
    subtitleDesktop = '22px',
    subtitleMobile = '20px',
    MEDIUM_LARGE = "28px",
    VERY_SMALL="11px",
    SMALL = "14px",
    VERYLARGE = '23px',
    MEDIUM = '18px',
    MEDIUM_BIG = "23px",
    NORMAL = "20px",
    BIG = "30px",
}